keys:
  - &pc age1lxgv0sqxut6ekz9une8d4zzj4vkrlph58ewv5w6r6m0xxddw9dgs3j8q8r
  - &laptop age1lxgv0sqxut6ekz9une8d4zzj4vkrlph58ewv5w6r6m0xxddw9dgs3j8q8r
creation_rules:
  - path_regex: hosts/pc/secrets.yaml$
    key_groups:
      - age:
          - *pc
  - path_regex: hosts/laptop/secrets.yaml$
    key_groups:
      - age:
          - *laptop
