{
  lib,
  pkgs,
  username,
  ...
}:
let
  whitesur-kde-opaque = pkgs.whitesur-kde.overrideAttrs {
    pname = "whitesur-kde-opaque";
    installPhase = ''
      runHook preInstall

      mkdir -p $out/doc

      name= ./install.sh -w opaque

      mkdir -p $out/share/sddm/themes
      sddm/install.sh

      runHook postInstall
    '';
  };

  qtctFormat = pkgs.formats.ini {
    listToValue = values: lib.concatStringsSep ", " values;
  };

  # Generated by qt5ct when "WhiteSur-opaqueDark" theme was selected.
  qtct-style-colors = qtctFormat.generate "style-colors.conf" {
    ColorScheme = {
      active_colors = [
        "#ffdedede"
        "#ff656565"
        "#ff5a5a5a"
        "#ff555555"
        "#ff202020"
        "#ff3c3c3c"
        "#ffdedede"
        "#ffffffff"
        "#ffdedede"
        "#ff242424"
        "#ff242424"
        "#ff000000"
        "#ffa0b4f8"
        "#ffffffff"
        "#ff3484e2"
        "#ff452886"
        "#ff2d2d2d"
        "#ff000000"
        "#ff333333"
        "#ffdedede"
        "#80dedede"
      ];
      disabled_colors = [
        "#ffbfbfbf"
        "#ff656565"
        "#ff5a5a5a"
        "#ff555555"
        "#ff202020"
        "#ff3c3c3c"
        "#ffbfbfbf"
        "#ffffffff"
        "#ffbfbfbf"
        "#ff242424"
        "#ff242424"
        "#ff000000"
        "#ffa0b4f8"
        "#66ffffff"
        "#ff3484e2"
        "#ff452886"
        "#ff2d2d2d"
        "#ff000000"
        "#ff333333"
        "#ffdedede"
        "#80dedede"
      ];
      inactive_colors = [
        "#ffdedede"
        "#ff656565"
        "#ff5a5a5a"
        "#ff555555"
        "#ff202020"
        "#ff3c3c3c"
        "#ffdedede"
        "#ffffffff"
        "#ffdedede"
        "#ff242424"
        "#ff242424"
        "#ff000000"
        "#ffa0b4f8"
        "#ffffffff"
        "#ff3484e2"
        "#ff452886"
        "#ff2d2d2d"
        "#ff000000"
        "#ff333333"
        "#ffdedede"
        "#80dedede"
      ];
    };
  };
in
{
  home-manager.users.${username} = {
    home = {
      packages = with pkgs; [
        libsForQt5.qtstyleplugin-kvantum
        qt6Packages.qtstyleplugin-kvantum
      ];

      sessionVariables = {
        QT_QPA_PLATFORM = "wayland;xcb";
      };
    };

    qt = {
      enable = true;
      platformTheme.name = "qtct";

      kvantum = {
        enable = true;
        themes = [
          pkgs.whitesur-kde
          whitesur-kde-opaque
        ];
        settings = {
          General.theme = "WhiteSur-opaqueDark";
        };
      };
    }
    // (lib.genAttrs [ "qt5ctSettings" "qt6ctSettings" ] (_: {
      Appearance = {
        icon_theme = "WhiteSur-dark";
        standard_dialogs = "xdgdesktopportal";
        style = "kvantum";

        custom_palette = true;
        color_scheme_path = toString qtct-style-colors;
      };
      Fonts = {
        fixed = "\"DejaVuSansM Nerd Font Mono,12\"";
        general = "\"DejaVu Sans,12\"";
      };
    }));
  };
}
