name: CI
on:
  pull_request:
  push: 
    branches: [main]
jobs:
  test:
    name: Check repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Intall Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Check repository
        run: nix flake check