name: Update dependencies
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0' # Run every day at 00:00
permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update flake.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Intall Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          github-token: ${{ secrets.PAT }}
      - name: Update flake.lock file
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          nix-options: --extra-experimental-features pipe-operators
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          pr-title: "chore(deps): update flake.lock"
          pr-labels: |
            type: deps
